### PR TITLE
This patch should fix #6

### LINKED ISSUE #6: Wrong mmultiscript child count when there’s only a single msub or msup following
I’ll send an example in private. And I’ll submit a pull request.

### PR DESCRIPTION
**Pull request by gimsieke**

### CODE REVIEW

**Comment by sbulka** [comment]
Seems good, some minimal testcases would be nice though.

Can you provide them?
I am pretty busy with other parts atm.

**Comment by gimsieke** [comment]
No, I’m also busy. Maybe @mhecher can write the tests?

**Comment by sbulka** [comment]
Will take a look this evening.

**Comment by gimsieke** [comment]
I created a PR #8 for the tests, but I couldn’t run it locally so i committed it straight away. We need to merge #7 first before the new tests will pass…

**Pull request merged**
